spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atmospeer
    username: testuser
    password: rj7783208232
  jpa:
    hibernate:
      ddl-auto: update

chatgpt:
  api-key: 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

youtube:
  api:
    key: AIzaSyCHMPzbV_1zONqcwOYkfucxAAPATywCb2s

unsplash:
  accessKey: Client-ID zbSIxL-dlgRb4nKwzf2TvWy6yDzIzb1E8iGHIoiueKQ